### ISSUE TITLE
Exception on DateField

### ISSUE THREAD

**Issue by witchi** [amahdy/person-service#3]
I got an exception on the Datefield, the date column values cannot be displayed on the PersonView side:

Unable to convert value of type java.time.LocalDate to presentation type class java.util.Date. No converter is set and the types are not compatible.

Could you check this?

**Comment by amahdy** [comment]
@witchi you are probably using Vaadin 7 with person-service 2.x
You should use 1.x instead: https://github.com/amahdy/person-service/tree/1.2

```xml
		<dependency>
			<groupId>org.vaadin.stepbystep</groupId>
			<artifactId>person-service</artifactId>
			<version>1.2</version>
		</dependency>
```

Or even better, use the new Vaadin 8 :-) I'm going to release a new video soon, meanwhile there is a migration guide/steps on this branch: https://github.com/amahdy/vaadin-stepbystep-demo-contacts/tree/vaadin7-to-vaadin8

**Comment by amahdy** [comment]
Please let me know if the issue persists.
